name: ignitestudios
favicon: null
layout_spectrum: 0.4754280182532966
typography_spectrum: 0.7937702648341656
title: 'Ignite Studios '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-7977951-16
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6633882904425263
  lightness: 0.8850269033573568
  saturation: 0.18369696475565434
  rhythmicContrast: 0.08950529620051384
purpose: []
