name: ignitestudios
favicon: null
layout_spectrum: 0
typography_spectrum: 0.43412
title: 'Ignite Studios '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-7977951-16
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1d1d'
    - '#b4b8bb'
    - '#005e7b'
    - '#1f9774'
    - '#c60c00'
  brandStrength: 0.5
  lightness: 0.8850269033573568
  saturation: 0.18369696475565434
  rhythmicContrast: 0.5
purpose: []
